sdhz152/android_vendor_cm

- prebuilt/common/etc/apns-conf.xml
This change updates the APN settings, removing the proxy and the port. 
This, according to movistar itself, makes the connection slower and 
will be shut down soon.
More info on their forum: 
https://foro.movistar.com.ar/threads/43044-NOVEDAD-Apagado-de-Proxy
Change-Id: I705e6ed2237503ee67c7371bf3595b461dfbbd9c
> apn: Updating Movistar Argentina APN

- prebuilt/common/bin/backuptool.functions
Without -d, we copy the file sysmlinked rather than the symlink.
Change-Id: Ie0fdd43f29e53334464188c846dd7a3b7bb770cc
> backuptool: Preserve symlinks

- overlay/common/vendor/cmsdk/packages/CMSettingsProvider/res/values/defaults.xml
With Android N this feature became less relevant since a subset of
the toggles is available without fully expanding the notification
panel. This gives better access to the notifications with almost no
functionality loss.
Change-Id: Idb66472b77e60f4ae753c5dd00f6588566cc3c63
> Disable quick pulldown by default

- build/tools/extract_utils.sh
Currently, the priority of the src and dest is inverted between
pulling from adb and pulling from a system dump.
Assume that we have a camera wrapper and write the proprietary-files.txt
lib/hw/camera.msm8996.so:lib/hw/camera.vendor.msm8996.so
If we pull from a phone running Lineage that has both files, we get
camera.vendor.msm8996.so
as the pulled blob.  If we take the exact same build and pull it
from the system dump (aka, your own $OUT directory that built the
installed software) you get
camera.msm8996.so
pull instead!
Make both paths follow the same logic so that you get the same
file independent of the source.
Change-Id: I479e0ae765339cc38fa05fcaad7943c528129463
> extract-utils: Fix handling of pulling src:dest pairs from dumps

- build/tools/extract_utils.sh
* On some machines, LC_ALL=C is set, causing the sort
order of makefiles to be different than those without
this locale change that is set
* Set LC_ALL=C on all machines for consistent ordering
* From 'man sort':
The locale specified by the environment affects sort order.
Set LC_ALL=C to get the traditional sort order that uses native byte values.
* Thanks to haggertk and rashed for verifying this for me
Change-Id: I5bbb94b0dfe599a67036de4312e8af913e9b8d30
Signed-off-by: Paul Keith <javelinanddart@aidenswann.com>
> extract_utils: Fix locale issue with sort

- config/common_full_tv.mk
This is required for all ATV builds. SUW will crash looking up the
wifi activity is it isn't installed.
Change-Id: Iccc982f46963024c065ac0b7c578ad60eb4d7d7a
> Add TvSettings to common tv config.

- prebuilt/common/etc/apns-conf.xml
The proxy prevents mobile data from working
(e.g. loading a webpage results in ERR_EMPTY_RESPONSE).
On all the mobile phones I've inserted the SIM in,
when the APN's are obtained automatically
this parameter is not set to any value.
Also remove unnecessary parameters and correct authentication type.
Change-Id: I16592de4555fb8ab3fe502b3b39779720c344afb
> apns: Remove proxy for the "TIM WAP" APN

- prebuilt/common/etc/apns-conf.xml
8ta has been rebranded to TelkomSA
Change-Id: I678099a2148cdc3ad773c3b1d93b9fa7bb417eff
> apn: Updating TelkomSA from 8ta South Africa APN

- sepolicy/untrusted_app.te
avc:  denied  { find } for service=profile pid=7970 uid=10086 scontext=u:r:untrusted_app:s0:c512,c768
tcontext=u:object_r:cm_profile_service:s0 tclass=service_manager permissive=1
java.lang.RuntimeException: Unable to start activity ComponentInfo{foo.bar/foo.bar.Activity}: java.lang.SecurityException:
You do not have permissions to change the Profile Manager.: Neither user 10086 nor current process has cyanogenmod.permission.MODIFY_PROFILES.
Ticket: BUGBASH-174
Change-Id: If8706177bf6eef8d5e4c73da4f00cc053987d1ed
Signed-off-by: Joey Rizzoli <joey@lineageos.org>
> cm: allow apps to find profile manager service

- sepolicy/seapp_contexts
An user-installed app with the cmfm package name could take advantage of this
Change-Id: I707df3043b9cd73cefcdea4ad0a28632f78089be
Signed-off-by: Joey Rizzoli <joey@lineageos.org>
> cm: remove special access to unused cmfm

- build/tools/roomservice.py
This change correctly handles devices with underscores in their
name even if there is a device with the same name after the last
underscore (spyder, umts_spyder) by not allowing any underscores
in the manufacturers name.
Without this change, spyder gets resolved to:
device/motorola_umts/spyder
device/motorola/spyder
Only the last one is valid.
With this change, both spyder and umts_spyder get resolved correctly.
Change-Id: I0c95ff126d827a2d6b58875dfcb9327e999f4913
> roomservice: handle devices with underscores

- build/tasks/kernel.mk
Commit 7fb9251dfcc7a0876c8fb906338452204942144a modified
the expansion in an illegal way.
Fix the broken env variable.
Change-Id: Ib3029fa995d6a4b0416887a2ef2e4792c9e6bb27
> kernel: Fix broken C_INCLUDE_PATH for Darwin

- overlay/common/frameworks/base/packages/SystemUI/res/values/config.xml
Globally enable full alarm info in quick settings drawer.
Screenshots: https://goo.gl/photos/ycuvZZFD1ssyWu8B6
This detailed info is pretty useful why not enable it for all devices.
Change-Id: I46ccc3547922b6ab5fdcf8798bd5269b7465a92d
Signed-off-by: Sebastian Haderecker <sebastian.haderecker@gmail.com>
> Show full alarm info

- prebuilt/common/bin/backuptool.sh
If /system is empty, /tmp/addon.d/ will not exist, "*sh" won't be
expanded, md5sum will not generate any output and the variable $s
will be empty. Therefore grep, which will receive only one arg, will
start to read the standard input and never exit, causing the
installation to never end. Fix this checking whether we have files
to read or not.
Change-Id: I656eab42e54b3f81da8c5ac81374b9deddcf8484
> fix check_blacklist function to work on wiped /system partition

- build/tools/repopick.py
In case of conflict, reset to initial state by aborting the cherry-pick,
leaving the working directory clean
Change-Id: I2353b92254b67ea49835bc88b6fc9bc3910b5107
> repopick: Add 'reset' option

- build/core/qcom_target.mk
Currently, using project-set-path is blocking us from overriding the pathmap
for the audio, display, and media HALs, so set them with set-device-specific-path
to allow overriding the HALs with USE_DEVICE_SPECIFIC_* and DEVICE_SPECIFIC_*_PATH
Change-Id: Iee3723cf251d0f485a77a17fd61cb62178833582
> qcom: Allow setting custom audio, display, and media HALs

- build/envsetup.sh
* ZSH errors out when it doesn't find anything in $OUT/system/lib/modules/.
* So add a check to avoid error while using installboot() with a target
that doesn't have modules enabled.
Change-Id: Ibe66f6962943e9b90c7059a4c9b4ded558318326
> envsetup: Fix installboot on ZSH

- build/core/qcom_target.mk
* Use msm8996 HAL for 8953 & 8937 since they share the exact same
git history sha1 in all 7.0+ released tags.
Change-Id: I764a9a092b6d530de8a9b9e6e54f41c0b5d8a593
> qcom_target: Commonize UM target HALs

- build/tools/extract_utils.sh
Skip the extraction of pinned files if the ones currently available
have the expected sha1. If we don't, we will overwrite pinned files
with potentially incorrect files when the current vendor files are
not moved to a temporary directory (i.e. when not cleaning vendor).
Change-Id: I640d6bf2ed98eb366a4df17f0ebeaec81cb5274b
> extract_utils: Fix pinning when not cleaning vendor dir

- build/tasks/kernel.mk
The existing kernel module logic does not detect failed kernel module
builds.  This is because the module build logic is a long shell chain
that invokes make macros which are not intended to be used in this way.
The essense of the issue is that we get a shell chain that looks like:
cmd && cmd && var=value; cmd && var=value; cmd;
The shell breaks this into three separate commands.  The first builds
the modules.  The other two are the macro invocations.  So the result
of the command is the result of the last macro invocation, which will
always succeed even if the modules fail to build.
The issue is made worse by the existing build rule conflating the built
kernel modules and the installed kernel modules.
Fix this by reducing the built kernel module command to a single shell
command and …
> cm: build: kernel: Rework kernel module logic

- build/templates/extract-files.sh
* Previously, you could just specify a SRC directly
after './extract-files', and it would work, but
now, the arg '-p/--path' is required for the same
behavior to be applied for the extraction
* Add a catch-all case that just sets SRC if the arg
doesn't match any of the args that we care about
* Make the ordering of the cases alphabetical
Change-Id: Ia2ad42d444904ead6b3bd6d910af363eb7f015cc
> extract-files: Bring back old behavior for SRC

- build/tools/extract_utils.sh
* This way it's automatically deleted at the end of the extraction
Change-Id: I77b3357875b8070d370f04c5a245f9aa3ca1939c
> extract_utils: Use temporary folder for system dump
